### ISSUE TITLE
whener i try to make a ressearch

### ISSUE THREAD

**Issue by Alexis-pog** [LeeTwentyThree/SubnauticaModManager#14]
whenever i go to the browse section of the mod manager i got this message that pops up

![image](https://user-images.githubusercontent.com/83509037/234918206-2de43347-eae7-4395-951b-ae53ae6adeb2.png)

**Comment by LeeTwentyThree** [comment]
Submodica server issue- resolved

**Comment by Alexis-pog** [comment]
thank you
