### ISSUE TITLE
Cannot enter website

### ISSUE THREAD

**Issue by WaiverBlock6109** [LeeTwentyThree/SubnauticaModManager#16]
I finally got the mod to work for Subnautica, but I cannot enter the website to make downloads due to this here.  In case the screenshot doesn't load right, it's the main page of Submodica blocked by a white bar with a blue-tinted background.  How to do I get around this problem?

![Screenshot 2023-06-05 190119](https://github.com/LeeTwentyThree/SubnauticaModManager/assets/135672733/05854aee-584a-49e6-b4fd-1cabe1f42a58)

**Comment by LeeTwentyThree** [comment]
Would be better to ask the developers of Submodica, I'll reach out to them and link this post.

**Comment by RamuneNeptune** [comment]
Click this and disable shields for Submodica, also disable ad-blockers or cookie blocking extensions if you have any
 ![](https://i.imgur.com/EPlXcO9.png)

**Comment by WaiverBlock6109** [comment]
It worked, thank you for a timely response.  I'll get to modding Subnautica right away
