### ISSUE TITLE
Browse Tab Not Working

### ISSUE THREAD

**Issue by Captainobviousyo** [LeeTwentyThree/SubnauticaModManager#17]
![image](https://github.com/LeeTwentyThree/SubnauticaModManager/assets/85375190/74696121-670c-4df3-a6eb-6e36c45c7ee2)
I already tried to remove the temp file in SNModManager but it still won't work

**Comment by Captainobviousyo** [comment]
Nvm I fixed it

**Comment by rylanhillalbert-oss** [comment]
do you have mac

**Comment by SpiralshapeDev** [comment]
I had windows at the time and, I believe that the website the mod browser uses called "Submodica" no longer exists so the in-game mod browser also no longer functions
