### ISSUE TITLE
Modmanager UI scaling on 2560x1080 seem to be off

### ISSUE THREAD

**Issue by liesemans** [LeeTwentyThree/SubnauticaModManager#2]
See picture
![Subnautica_ModManager_scaling issue](https://user-images.githubusercontent.com/122680949/212475012-0e88e9dd-edf8-4bd0-9536-e16da652751a.jpg)

**Comment by LeeTwentyThree** [comment]
Tbh I thought it was supposed to not scale horizontally at all. I’ll work on a fix very soon.

**Comment by LeeTwentyThree** [comment]
Issue should be resolved https://github.com/LeeTwentyThree/SubnauticaModManager/releases/tag/1.0.3
