### ISSUE TITLE
Cannot install mods from nexus, they don't show up and can't be installed.

### ISSUE THREAD

**Issue by xtexecute** [LeeTwentyThree/SubnauticaModManager#21]
![Ekran görüntüsü 2023-09-27 214228](https://github.com/LeeTwentyThree/SubnauticaModManager/assets/146252866/a137949b-583e-4953-92c7-35b42b0d9fa2)
![Ekran görüntüsü 2023-09-27 214327](https://github.com/LeeTwentyThree/SubnauticaModManager/assets/146252866/8e910ed0-cabc-4b56-9a1e-e1e6529046ed)

**Comment by LeeTwentyThree** [comment]
The mods you have that aren’t working are for the legacy version of Subnautica and will be updated eventually.
