### ISSUE TITLE
Add Simplified Chinese Localization Support

### ISSUE THREAD

**Issue by ilworkcn** [LeeTwentyThree/SubnauticaModManager#29]
I have translated the lang file.
And i have confirmed that the format of the json is correct and replace it with "English.json", and it works properly.
The translated texts are proofread by myself.
Thank you for developing this great mod, if you have time and wish, please add support for Simplified Chinese!
[SimplifiedChinese.json](https://github.com/user-attachments/files/16308867/SimplifiedChinese.json)

**Comment by LeeTwentyThree** [comment]
Oh, thanks very much! I will add this now.

**Comment by LeeTwentyThree** [comment]
Incredible work, again thanks. The changes are now released in 1.2.3 and you have been credited properly.

https://github.com/LeeTwentyThree/SubnauticaModManager/releases/tag/1.2.3
