### ISSUE TITLE
Updating/Installing non-functional

### ISSUE THREAD

**Issue by MMZTimeLord** [LeeTwentyThree/SubnauticaModManager#3]
Mod zip files not being removed or properly installed from SNModManager\ModDownloads. Not sure if it's a zip file structure issue or permissions used when running subnautica. Restart is prompted and looks like the files installed/updated, but everything remains the same after game restart.

**Comment by LeeTwentyThree** [comment]
Appears to be caused by an exception related to assembly loading of Newtonsoft.Json.dll.

![Exception](https://user-images.githubusercontent.com/31892011/212586100-992d18ed-04c7-4cac-b47d-cb1a9807a316.png)

**Comment by LeeTwentyThree** [comment]
@liesemans if you're still there.

I have made an alternate version of the mod manager that outputs a specific log file to `Subnautica.stable\SNModManager\installation-log.txt`.

Can you run it and send that file? [SubnauticaModManager-installation_test-1.zip](https://github.com/LeeTwentyThree/SubnauticaModManager/files/10430703/SubnauticaModManager-installation_test-1.zip)

**Comment by LeeTwentyThree** [comment]
I also have created a version that uses a different version of Newtonsoft.Json.dll, which seems to be a problematic file. This version _also_ has logging so perhaps use it instead of the one sent above.

[SubnauticaModManager-installation_test-2.zip](https://github.com/LeeTwentyThree/SubnauticaModManager/files/10430736/SubnauticaModManager-installation_test-2.zip)

**Comment by liesemans** [comment]
Hi @LeeTwentyThree , of course I'm still here.....
I tested your latest version 'test-2' of the modmanager and it all works fine now!!
I installed mods two times (logfile is attached)
Great work...thanks.

[installation-log.txt](https://github.com/LeeTwentyThree/SubnauticaModManager/files/10432241/installation-log.txt)

**Comment by MMZTimeLord** [comment]
@LeeTwentyThree Tested just now. Properly disables existing mods. Even smart enough to keep it disabled when I installed the same mod WHILE it was disabled. All works fine now. Thanks for the hard work!
