### ISSUE TITLE
Browse - Loading mods freeze

### ISSUE THREAD

**Issue by JLSkyzer** [LeeTwentyThree/SubnauticaModManager#5]
![image](https://user-images.githubusercontent.com/60830349/213470778-be5521b6-b99e-40ba-879d-6a5f2864ccd0.png)

**Comment by LeeTwentyThree** [comment]
Must be an exception happening somewhere. If you clear the image cache does it still occur? I can look into it soon

**Comment by LeeTwentyThree** [comment]
Unable to recreate. Perhaps send a log file? Personally mine can be found at `C:\Users\[YOUR USER NAME HERE]\AppData\LocalLow\Unknown Worlds\Subnautica\Player.log`

**Comment by JLSkyzer** [comment]
ok

**Comment by JLSkyzer** [comment]
send that
[Player.log](https://github.com/LeeTwentyThree/SubnauticaModManager/files/10468840/Player.log)

**Comment by JLSkyzer** [comment]
> Must be an exception happening somewhere. If you clear the image cache does it still occur? It’s in the SNModManager folder, in a hidden folder named Temp. I can look into it soon

How i do that ?
And i can't see the hidden folder

**Comment by JLSkyzer** [comment]
Ho ! i see the temp forlder, what i do ?

**Comment by JLSkyzer** [comment]
ok that work thx ! is the imageCache

**Comment by LeeTwentyThree** [comment]
You can just delete the folder entirely. The log Is too long for me to parse right now perhaps send one that was generated right after having the loading freeze

**Comment by LeeTwentyThree** [comment]
> ok that work thx ! is the imageCache

Issue is resolved? Nice
