### ISSUE TITLE
Most mod manager features do not properly function on macOS

### ISSUE THREAD

**Issue by kiararey** [LeeTwentyThree/SubnauticaModManager#8]
<img width="1638" alt="Screenshot 2023-01-21 at 12 50 08 PM" src="https://user-images.githubusercontent.com/24264174/213882545-d9f558b5-db32-4b05-8d71-f59b6ad5d16c.png">
Basically clicking these does not do anything, but it does recognize that I have zipped files in the appropriate folder

**Comment by LeeTwentyThree** [comment]
The Subnautica Mod Manager was never meant to support macOS, I had no idea most mods even worked with BepInEx. Until a Subnautica modder who runs it can test it, I don't think it's possible to do anything about these problems.

**Comment by LeeTwentyThree** [comment]
Hopefully you don't mind, because I'm going to hijack your issue page to make it clear to users on this page that currently there is no way to use this mod on macOS. Sorry about that :(
